# -*- coding: utf-8 -*-
"""Module 1- Python Algorithm Problems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189sSyXa2tY1RMD4z8v6yfvV7vllQzg9X

**1.9 Ödev Önerileri - Modül 1**

**1. Basit Dönüştürücü: Metre-Feet, Kilogram-Pound dönüştürücüsü yapın**  
✔ 1 metre = 3.28084 feet  
✔ 1 kilogram = 2.20462 pound
"""

metre = float(input("Metre değeri: "))
feet = metre * 3.28084
print(f"{metre} metre = {feet} feet")
print(f"{metre} metre = {feet:.1f} feet")
print(f"{metre} metre = {feet:.2f} feet")

kg = float(input("Kilogram değeri: "))
pound = kg * 2.20462
print(f"{kg} kilogram = {pound} pound'dur")
print(f"{kg} kilogram = {pound:.1f} pound'dur")
print(f"{kg} kilogram = {pound:.2f} pound'dur")

"""**2. Kişisel Bütçe: Gelir ve giderleri alıp kalan parayı hesaplayan program**"""

gelir = float(input("Maaş: "))
 kira = float(input("Kira: "))
 fatura = float(input("Faturalar: "))
ulaşım = float(input("Ulaşım: "))
yemek = float(input("Yemek: "))
diğer = float(input("Diğer: "))

gider = kira + fatura + ulaşım + yemek + diğer
kalan = gelir - gider

print(f"Gider: {gider:.2f} TL")
print(f"Kalan: {kalan:.2f} TL")
if kalan >= 0:
      print ("Bakiye: Pozitif ")
else:
      print("Bakiye: Negatif. Borcunuz var ")



gelir = float(input("Maaş: "))
 kira = float(input("Kira: "))
 fatura = float(input("Faturalar: "))
ulaşım = float(input("Ulaşım: "))
yemek = float(input("Yemek: "))
diğer = float(input("Diğer: "))

gider = kira + fatura + ulaşım + yemek + diğer
kalan = gelir - gider

print(f"Gider: {gider:.2f} TL")
print(f"Kalan: {kalan:.2f} TL")
if kalan >= 0:
      print ("Bakiye: Pozitif ")
else:
      print("Bakiye: Negatif. Borcunuz var ")

"""**3. Yaş Gün Hesaplayıcı: Doğum tarihinden bugüne kaç gün yaşandığını hesaplayan program**"""

from datetime import datetime
doğum_tarihi = input("Doğum tarihinizi (GG/AA/YYYY) formatında giriniz: ")
gun, ay, yıl = map(int, doğum_tarihi.split("/"))

doğum = datetime(yıl, ay, gun)
bugün = datetime.now()

yaş =(bugün-doğum).days
print(f"Toplamda {yaş} gündür yaşıyorsun.")

"""**4. İndirim Hesaplayıcı: Ürün fiyatı ve indirim oranını alıp yeni fiyatı hesaplayan program**"""

fiyat = float(input("Ürün fiyatı (TL): "))
indirim_orani = float(input("İndirim oranı (%): "))

indirim = fiyat * indirim_orani / 100
yeni_fiyat = fiyat - indirim

print(f"\nİndirim tutarı: {indirim:.2f} TL")
print(f"İndirimli fiyat: {yeni_fiyat:.2f} TL")

"""**5. Restoran Hesabı: Yemek fiyatı, bahşiş oranı ve kişi sayısını alıp kişi başı tutarı hesaplayan program**"""

hesap = float(input("Toplam yemek fiyatı (TL): "))
bahsis_orani = float(input("Bahşiş oranı (%): "))
kisi_sayisi = int(input("Kişi sayısı: "))

bahsis = hesap * bahsis_orani / 100
toplam = hesap + bahsis
kisi_basi = toplam / kisi_sayisi

print("\n--- SONUÇ ---")
print(f"Bahşiş: {bahsis:.2f} TL")
print(f"Toplam hesap: {toplam:.2f} TL")
print(f"Kişi başı ödeme: {kisi_basi:.2f} TL")