# -*- coding: utf-8 -*-
"""python-exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUNh5E0cMuDjoqvqWCyBF6p1f8-u9PO8

**Sınıf Geçme Sistemi: Kullanıcıdan notları alıp sınıf geçip geçmediğini, harf notunu gösteren program**
"""

vize = float(input("Vize Notu (0-100): "))
final = float(input("Final Notu (0-100): "))
odev = float(input("Ödev Notu (0-100): "))


if not (0 <= vize <= 100 and 0 <= final <= 100 and 0 <= odev <= 100):
    print("Hata: Tüm notlar 0-100 aralığında olmalı!")
    exit()

ortalama = vize * 0.3 + final * 0.5 + odev * 0.2

# Harf notu
if ortalama >= 90:
    harf = "AA"
elif ortalama >= 80:
    harf = "BB"
elif ortalama >= 70:
    harf = "CC"
elif ortalama >= 60:
    harf = "DD"
else:
    harf = "FF"

durum = "Geçti" if ortalama >= 50 else "Kaldı"

print(f"\nOrtalama: {ortalama:.2f}")
print(f"Harf Notu: {harf}")
print(f"Durum: {durum}")

"""**Vergi Hesaplayıcı: Gelir düzeyine göre farklı oranlarda vergi hesaplayan program**"""

gelir = float(input("Yıllık geliriniz (TL): "))

if gelir < 0:
    print("Hata: Gelir negatif olamaz!")
    exit()

# Vergi dilimleri
if gelir <= 20000:
    vergi = gelir * 0.10      # %10
elif gelir <= 50000:
    vergi = 20000 * 0.10 + (gelir - 20000) * 0.15
elif gelir <= 100000:
    vergi = 20000 * 0.10 + 30000 * 0.15 + (gelir - 50000) * 0.20
else:
    vergi = 20000 * 0.10 + 30000 * 0.15 + 50000 * 0.20 + (gelir - 100000) * 0.30

print(f"Ödemeniz gereken vergi: {vergi:.2f} TL")

"""**Restoran Sipariş Sistemi: Menüden seçim yapıp toplam tutarı hesaplayan program**"""

menu = {
    "1": ("Hamburger", 80),
    "2": ("Pizza", 120),
    "3": ("Kola", 20),
    "4": ("Tatlı", 45)
}

print("\nMENÜ:")
for k, v in menu.items():
    print(f"{k}. {v[0]} - {v[1]} TL")

toplam = 0

while True:
    secim = input("\nSipariş numarası (Çıkış için q): ")

    if secim == "q":
        break

    if secim not in menu:
        print("Hatalı seçim!")
        continue

    adet = int(input("Kaç adet?: "))
    if adet <= 0:
        print("Geçersiz adet!")
        continue

    toplam += menu[secim][1] * adet
    print(f"Ekleme başarılı. Ara toplam: {toplam} TL")

print(f"\nToplam tutar: {toplam} TL")
print("Teşekkür ederiz!")

"""**Basit Oyun: Kullanıcı ile bilgisayarın taş-kağıt-makas oynadığı program**"""

import random

print("=== Taş - Kağıt - Makas ===")

secenekler = ["taş", "kağıt", "makas"]

kullanici = input("Seçiminiz (taş/kağıt/makas): ").lower()
if kullanici not in secenekler:
    print("Hatalı seçim!")
    exit()

bilgisayar = random.choice(secenekler)

print(f"Bilgisayar: {bilgisayar}")

# Oyun kuralları
if kullanici == bilgisayar:
    print("Berabere!")
elif (kullanici == "taş" and bilgisayar == "makas") or \
     (kullanici == "kağıt" and bilgisayar == "taş") or \
     (kullanici == "makas" and bilgisayar == "kağıt"):
    print("Kazandınız!")
else:
    print("Kaybettiniz!")

"""**Kredi Kartı Doğrulama: Kredi kartı numarasının geçerli olup olmadığını kontrol eden program (Luhn algoritması)**"""

kart = input("Kart numarasını girin (boşluksuz): ")

if not kart.isdigit():
    print("Hata: Kart numarası sadece rakamlardan oluşmalıdır!")
    exit()

# Luhn algoritması
toplam = 0
ters = kart[::-1]

for i, hane in enumerate(ters):
    n = int(hane)

    if i % 2 == 1:  # Çift indeksli haneler (soldan bakınca)
        n *= 2
        if n > 9:
            n -= 9

    toplam += n

if toplam % 10 == 0:
    print("Kart geçerli ✔️")
else:
    print("Kart geçersiz ❌")