# -*- coding: utf-8 -*-
"""restaurant_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAbqeDb6msa05Z76tDXZOujuPTpFVpKg

Restoran Hesabı: Yemek fiyatı, bahşiş oranı ve kişi sayısını alıp kişi başı tutarı hesaplayan program      
Restaurant Calculator: A program that calculates the amount per person based on the meal price, tip rate, and number of people.
"""

yemek_fiyati = float(input("Toplam yemek fiyatı: "))
bahsis_orani = float(input("Bahşiş oranı (%) girin: "))
kisi_sayisi = int(input("Kişi sayısı: "))

bahsis_miktari = yemek_fiyati * (bahsis_orani / 100)
toplam_hesap = yemek_fiyati + bahsis_miktari
kisi_basi = toplam_hesap / kisi_sayisi

print(f"\nBahşiş miktarı: {bahsis_miktari:.2f} TL")
print(f"Toplam hesap: {toplam_hesap:.2f} TL")
print(f"Kişi başı ödenecek tutar: {kisi_basi:.2f} TL")

"""fonksiyonla yaparsak"""

def restaurant_calculate(mealPrice, tipRate, numberOfPeople):
    tipAmount = mealPrice * (tipRate / 100)
    totalAmount = mealPrice + tipAmount
    perPerson = totalAmount / numberOfPeople
    return tipAmount, totalAmount, perPerson


# Kullanıcıdan değerleri alma
mealPrice = float(input("Toplam yemek fiyatı: "))
tipRate = float(input("Bahşiş oranı (%) girin: "))
numberOfPeople = int(input("Kişi sayısı: "))

t, tot, p = restaurant_calculate(mealPrice, tipRate, numberOfPeople)

print(f"\nBahşiş miktarı: {mp:.2f} TL")
print(f"Toplam hesap: {tr:.2f} TL")
print(f"Kişi başı ödenecek tutar: {np:.2f} TL")