# -*- coding: utf-8 -*-
"""tax_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQUx9blZzWyr1_dGOFoqjD8j-c5kLpz8

Vergi Hesaplayıcı: Gelir düzeyine göre farklı oranlarda vergi hesaplayan program    
Tax Calculator: Program that calculates tax rates at different rates based on income level

** Her vergi dilimi için:    
O dilime düşen gelir bulunur -> O kısmın vergi oranı ile çarpılır  -> Tüm dilimlerin vergisi toplanır
| Gelir Aralığı      | Vergi Oranı |
| ------------------ | ----------- |
| 0 – 10.000 TL      | %10         |
| 10.001 – 50.000 TL | %20         |
| 50.000 TL üzeri    | %30         |
"""

gelir = float(input("Gelirinizi girin: "))

if gelir <= 10000:
    vergi = gelir * 0.1
elif gelir <= 50000:
    vergi = 10000 * 0.1 + (gelir - 10000) * 0.2
else:
  vergi = 10000 * 0.1 + 40000 * 0.2 + (gelir - 50000) * 0.3     # 50000-10000=40000

print(f"Ödemeniz gereken vergi: {vergi} TL")

"""**fonksiyon ile çözersek**"""

# vergi_hesapla adında bir fonksiyon tanımla. Fonksiyon, geliri(g) parametresini alıyor ve vergiyi(v) hesaplayıp döndürüyor.

def vergi_hesapla(g):

    if g <= 10000:
        v = g * 0.1
    elif g <= 50000:
        v = 10000 * 0.1 + (g - 10000) * 0.2
    else:
        v = 10000 * 0.1 + 40000 * 0.2 + (g - 50000) * 0.3
    return v

g = float(input("Gelirinizi girin: "))
odenecek_vergi = vergi_hesapla(g)
print(f"Ödemeniz gereken vergi: {odenecek_vergi} TL")

"""**Dinamik hali:** vergi dilimi olursa olsun otomatik hesaplasın      
Bunun için dilimler listesi ile istediğin kadar kademeli vergi dilimi tanımla.
Her dilim (gelir_sinir, vergi_orani) şeklinde.
Fonksiyon, geliri soldan sağa dilimlere göre kontrol eder ve doğru vergi toplamını hesaplar.
float('inf') kullanarak son dilimi “sonsuz” olarak belirledik, böylece üst sınır olmadan çalışır.
"""

"""
    Gelire göre kademeli vergi hesaplar.
    dilimler = [(gelir_sinir, oran), ...]
    Örnek:
        [(10000, 0.1), (50000, 0.2), (float('inf'), 0.3)]
"""
def vergi_hesapla_dinamik(gelir, dilimler):

    vergi = 0
    onceki_sinir = 0

    for sinir, oran in dilimler:
        if gelir > sinir:
            vergi += (sinir - onceki_sinir) * oran
            onceki_sinir = sinir
        else:
            vergi += (gelir - onceki_sinir) * oran
            break

    return vergi

# Örnek dilimler: 0-10.000: %10, 10.001-50.000: %20, 50.001 ve üzeri: %30
dilimler = [(10000, 0.1), (50000, 0.2), (float('inf'), 0.3)]

gelir = float(input("Gelirinizi girin: "))
odenecek_vergi = vergi_hesapla_dinamik(gelir, dilimler)
print(f"Ödemeniz gereken vergi: {odenecek_vergi} TL")

"""**Geliri her dilime göre ayrı ayrı gösteren bir vergi hesaplama fonksiyonu hazırlarsak böylece hangi dilimden ne kadar vergi ödendiğini net görebiliriz.**"""

def vergi_hesapla_detayli(gelir, dilimler):
    """
    Gelire göre kademeli vergi hesaplar ve her dilimin katkısını gösterir.
    dilimler = [(gelir_sinir, oran), ...]
    Örnek:
        [(10000, 0.1), (50000, 0.2), (float('inf'), 0.3)]
    """
    vergi = 0
    onceki_sinir = 0
    detaylar = []

    for sinir, oran in dilimler:
        if gelir > sinir:
            dilim_tutari = sinir - onceki_sinir
            vergi_dilim = dilim_tutari * oran
            detaylar.append((onceki_sinir, sinir, oran, vergi_dilim))
            vergi += vergi_dilim
            onceki_sinir = sinir
        else:
            dilim_tutari = gelir - onceki_sinir
            vergi_dilim = dilim_tutari * oran
            detaylar.append((onceki_sinir, gelir, oran, vergi_dilim))
            vergi += vergi_dilim
            break

    return vergi, detaylar

# Örnek dilimler: 0-10.000: %10, 10.001-50.000: %20, 50.001 ve üzeri: %30
dilimler = [(10000, 0.1), (50000, 0.2), (float('inf'), 0.3)]

gelir = float(input("Gelirinizi girin: "))
odenecek_vergi, detaylar = vergi_hesapla_detayli(gelir, dilimler)

print(f"\nToplam ödenecek vergi: {odenecek_vergi} TL\n")
print("Her dilimin vergi katkısı:")
for baslangic, bitis, oran, vergi_dilim in detaylar:
    print(f"{baslangic} - {bitis} TL arası: %{int(oran*100)} → {vergi_dilim} TL")